# Generated by Django 4.1.3 on 2022-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_avatar_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='client_booking_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
